"""
Q. Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

A. 4613732
"""


def sum_of_even_fib_terms(n):
    res = 0
    a, b, c = 2, 1, 1
    while a < n:
        res += a * (a % 2 == 0)
        a, b, c = a + b, a, b

    return res


if __name__ == "__main__":
    n = int(4e6)
    print(
        "Sum of even Fibonacci terms (each < {}): {}".format(
            n, sum_of_even_fib_terms(n)
        )
    )
