"""
Q: Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle      T_n = n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal    P_n = n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal     H_n = n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

A: 1533776805
"""


def next_triangular_pentagonal_hexagonal():
    nt, np, nh = 285, 165, 143
    t = lambda n: n * (n + 1) // 2
    p = lambda n: n * (3 * n - 1) // 2
    h = lambda n: n * (2 * n - 1)

    while True:
        nt += 1

        while p(np) < t(nt):
            np += 1

        while h(nh) < t(nt):
            nh += 1

        if t(nt) == p(np) == h(nh):
            return t(nt)


if __name__ == "__main__":
    print(
        "Next triangular, pentagonal, hexagonal number after 40755: {}".format(
            next_triangular_pentagonal_hexagonal()
        )
    )
